baseurl: /
title: "ChaosEco"
theme: "Mainroad"

# 中文显示配置
languageCode: "zh-cn"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
enableEmoji: true

# 每页显示多少条博文标题
paginate: '10'

#disqusShortname: 'chaoseco'
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
googleAnalytics: ''
footnotereturnlinkcontents: "↩"
rssLimit: 100


Author:
  avatar: img/avatar1.jpg
  bio: Nothing known.
  name: ChaosEco
  
  
permalinks:
  posts = "/post/:year-:month-:slug/"
  projects = "/project/:year-:slug/"
  

menu:
  main:
    - name: "首页"
      identifier: "mainpage"
      url: "/"
      weight: 10
    - name: "文章列表"
      identifier: "posts"
      url: "/post/"
      weight: 20
    - name: "所有分类"
      identifier: "categories"
      url: "/categories/"
      weight: 30
    - name: "所有标签"
      identifier: "tags"
      url: "/tags/"
      weight: 40
    - name: "关于我"
      identifier: "about"
      url: "/about/"
      weight: 50
      

Params:
  authorbox: yes
  description: "Personal website of Chao Xu"
  mainSections:
    - post
    - docs
  opengraph: yes
  pager: yes
  googleFontsLink: "/res/font/opensans/opensans.css"
  readmore: true
  sidebar: 
    home: right   # Configure layout for home page
    list: false   # Configure layout for list pages: right/left/false
    single: false # Configure layout for single pages
    widgets:
      - search
      - recent
      - categories
      - taglist
      - social
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
    social:
      github: "https://github.com/chaoseco"
      email: "chaoseco@fake.com"
  logo:
    # image: "img/avatar1.jpg"
    title: "Chaoseco"
    subtitle: "Life Recording"
  post_meta:
    - date
    - categories
  style:
    vars:
      highlightColor: "#d60000" # 页面高亮 (链接等) 颜色

