baseurl: /
title: "ChaosEco"
languageCode: "en-us"
paginate: '10'
theme: "Mainroad"
disqusShortname: 'chaoseco'
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
googleAnalytics: ''
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true
enableEmoji: true
rssLimit: 100


Author:
  avatar: img/avatar.png
  bio: Nothing known.
  name: Chao Xu
  
  
permalinks:
  posts = "/post/:year-:month-:slug/"
  projects = "/project/:year-:slug/"
  

menu:
  main:
    - name: "Post"
      url: "/post/"
      weight: 1
    - name: "Project"
      url: "/project/"
      weight: 2

  
Params:
  authorbox: yes
  description: "Personal website of Chao Xu"
  logo:
    image: "img/avatar1.png"
    title: "Chaoseco"
    subtitle: "Life Recording"
  mainSections:
    - post
    - docs
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar: 
    home: right   # Configure layout for home page
    list: false   # Configure layout for list pages: right/left/false
    single: false # Configure layout for single pages
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
